### ISSUE TITLE
Duplicate identifier in typings.

### ISSUE THREAD

**Issue by grundius** [mbrn/material-table#1675]
**Describe the bug**
After upgrading to 1.57.2, compiling with `tsc` (TS 3.7.5)  gives the following result:
```
node_modules/material-table/types/index.d.ts:231:3 - error TS2300: Duplicate identifier 'searchText'.

231   searchText?: string;
      ~~~~~~~~~~

node_modules/material-table/types/index.d.ts:234:3 - error TS2300: Duplicate identifier 'searchText'.

234   searchText?: string;
      ~~~~~~~~~~
```

I have the following dependencies in `package.json`:
```
        "@date-io/date-fns": "^1.3.11",
        "@material-ui/core": "^4.9.3",
        "@material-ui/icons": "^4.9.1",
        "@material-ui/lab": "^4.0.0-alpha.43",
        "@material-ui/pickers": "^3.2.10",
        "@material-ui/styles": "^4.9.0",
        "date-fns": "^2.9.0",
        "firebase": "^7.8.2",
        "formik": "^1.5.8",
        "formik-material-ui": "^1.0.2",
        "formik-material-ui-pickers": "0.0.8",
        "google-map-react": "^1.1.6",
        "inversify": "^5.0.1",
        "lodash": "^4.17.15",
        "material-table": "^1.57.2",
        "react": "^16.10.2",
        "react-async-component": "^2.0.0",
        "react-dom": "^16.10.2",
        "react-helmet": "^5.2.1",
        "react-redux": "^7.2.0",
        "react-router-dom": "^5.1.2",
        "redux": "^4.0.5",
        "redux-mock-store": "^1.5.3",
        "redux-saga": "^1.1.3",
        "reflect-metadata": "^0.1.13",
        "yup": "^0.27.0"
```

1.57.0 compiles fine.

**Expected behavior**
It compiles normally.

**Comment by tomwang2011** [comment]
it should be fixed by https://github.com/mbrn/material-table/pull/1624 right? Any ETA on when a new version with it will be released?

**Comment by iamchathu** [comment]
Seems fix has not yet reached to npm

**Comment by khelpix** [comment]
/ClientApp/node_modules/material-table/types/index.d.ts(231,3):
Duplicate identifier 'searchText'.  TS2300

**Comment by mfsjr** [comment]
This bug breaks material-ui tests, see https://github.com/mui-org/material-ui/issues/20296

**Comment by wareworks** [comment]
facing this issue since days. Any timeline for a fix?

**Comment by hikmert** [comment]
has anyone found a solution for this issue, by any chance?

**Comment by Domino987** [comment]
Should be fixed now
